server:
  port: 8761
  instance-id: ${spring.application.name}:${spring.application.instance_id:${spring.cloud.client.ip-address}}:${server.port}
spring:
  application:
    name: discovery-service
  main:
    banner-mode: off
  cloud:
    loadbalancer.ribbon.enabled: false # ribbon is in maintenance mode and should be replaced by spring-cloud-loadbalancer

eureka:
  server:
    peer-node-read-timeout-ms: 60000
    enableSelfPreservation: true
    eviction-interval-timer-in-ms: 10000
  instance:
    hostname: localhost
    instance-id: ${server.instance-id}
    preferIpAddress: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
logging:
  level:
    root: INFO
    com.netflix.discovery: WARN
    com.netflix.eureka: WARN
    c.n.e.registry.AbstractInstanceRegistry: ERROR # ignore WARN No remote registry available for the remote region us-east-1
