spring:
  application.name: wfs
  config:
    name: geoserver # load externalized configuration from geoserver.yml
    import:
      - classpath:geoserver_spring_boot_profiles.yml
      - classpath:geoserver_spring_cloud_profiles.yml
  # and always include the service specific settings from the profile
  profiles.include: ${spring.application.name}
  # also ask for geoserver.yml when loading the externalized config through a config-server
  cloud.config.name: geoserver

# Fixed per-service value to support conditional activation of extensions.
# This property is checked by @ConditionalOnGeoServerWFS
geoserver.service.wfs.enabled: true
geoserver.base-path: /wfs
---
spring.config.activate.on-profile: "bootstrap-standalone"
spring.config.import: ${standalone.config.location:file:/etc/geoserver/geoserver.yml}
---
# local profile, used for development only. Other settings like config and eureka urls in gs_cloud_bootstrap_profiles.yml
spring.config.activate.on-profile: local
server.port: 9101
management.server.port: 8101
