version: "3.8"

volumes:
  postgresql_config_data: # volume for postgresql data, used to store the geoserver config through jdbcconfig

#
# Configures all geoserver services to use the postgresql database server with jdbcconfig as catalog backend.
# Run with `docker-compose --compatibility -f docker-compose.yml -f docker-compose-jdbcconfig.yml up -d`
#

services:
  #catalog:
  #  command: echo "catalog-service disabled."
  database:
    # be sure geoserver.backend.jdbcconfig.initdb is set to true in application.yml at lease for the first app run
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: "${JDBCCONFIG_DBNAME}"
      POSTGRES_USER: "${JDBCCONFIG_USERNAME}"
      POSTGRES_PASSWORD: "${JDBCCONFIG_PASSWORD}"
    ports:
      - 54321:5432
    networks:
      - gs-cloud-network
    volumes:
      - postgresql_config_data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 1G


  wfs:
    environment:
      SPRING_PROFILES_ACTIVE: "${DEFAULT_PROFILES},jdbcconfig"
      JDBCCONFIG_URL: "${JDBCCONFIG_URL}"
      JDBCCONFIG_USERNAME: "${JDBCCONFIG_USERNAME}"
      JDBCCONFIG_PASSWORD: "${JDBCCONFIG_PASSWORD}"
    depends_on:
      - database

  wms:
    environment:
      SPRING_PROFILES_ACTIVE: "${DEFAULT_PROFILES},jdbcconfig"
      JDBCCONFIG_URL: "${JDBCCONFIG_URL}"
      JDBCCONFIG_USERNAME: "${JDBCCONFIG_USERNAME}"
      JDBCCONFIG_PASSWORD: "${JDBCCONFIG_PASSWORD}"
    depends_on:
      - database

  wcs:
    environment:
      SPRING_PROFILES_ACTIVE: "${DEFAULT_PROFILES},jdbcconfig"
      JDBCCONFIG_URL: "${JDBCCONFIG_URL}"
      JDBCCONFIG_USERNAME: "${JDBCCONFIG_USERNAME}"
      JDBCCONFIG_PASSWORD: "${JDBCCONFIG_PASSWORD}"
    depends_on:
      - database

  rest:
    environment:
      SPRING_PROFILES_ACTIVE: "${DEFAULT_PROFILES},jdbcconfig"
      JDBCCONFIG_URL: "${JDBCCONFIG_URL}"
      JDBCCONFIG_USERNAME: "${JDBCCONFIG_USERNAME}"
      JDBCCONFIG_PASSWORD: "${JDBCCONFIG_PASSWORD}"
    depends_on:
      - database

  webui:
    environment:
      SPRING_PROFILES_ACTIVE: "${DEFAULT_PROFILES},jdbcconfig"
      JDBCCONFIG_URL: "${JDBCCONFIG_URL}"
      JDBCCONFIG_USERNAME: "${JDBCCONFIG_USERNAME}"
      JDBCCONFIG_PASSWORD: "${JDBCCONFIG_PASSWORD}"
    depends_on:
      - database

  gwc:
    environment:
      SPRING_PROFILES_ACTIVE: "${DEFAULT_PROFILES},jdbcconfig"
      JDBCCONFIG_URL: "${JDBCCONFIG_URL}"
      JDBCCONFIG_USERNAME: "${JDBCCONFIG_USERNAME}"
      JDBCCONFIG_PASSWORD: "${JDBCCONFIG_PASSWORD}"
    depends_on:
      - database
