version: "3.8"

#
# Configures all geoserver services to use a shared data directory as catalog backend.
# Run with `docker-compose --compatibility -f docker-compose.yml -f docker-compose-shared_datadir.yml up -d`
# NOTE: Not ready for direct usage until deciding on a strategy to easily set up the shared data directory.
# Note the default data directory locatio is /opt/app/data_directory
# To set it to a different path, change the mount point and add the following env variable: GEOSERVER_DATA_DIR: </path/to/data_directory>

volumes:
  test_shared_data_directory:
    driver_opts:
      type: none
      o: bind
      device: $PWD/docker-compose_datadir
  
services:
  database:
    entrypoint: echo "database-service disabled."

  catalog:
    command: echo "catalog-service disabled."

  wfs:
    environment:
      SPRING_PROFILES_ACTIVE: "datadir"
    volumes:
      - test_shared_data_directory:/opt/app/data_directory

  wms:
    environment:
      SPRING_PROFILES_ACTIVE: "datadir"
    volumes:
      - test_shared_data_directory:/opt/app/data_directory

  wcs:
    environment:
      SPRING_PROFILES_ACTIVE: "datadir"
    volumes:
      - test_shared_data_directory:/opt/app/data_directory

  rest:
    environment:
      SPRING_PROFILES_ACTIVE: "datadir"
    volumes:
      - test_shared_data_directory:/opt/app/data_directory

  webui:
    environment:
      SPRING_PROFILES_ACTIVE: "datadir"
    volumes:
      - test_shared_data_directory:/opt/app/data_directory
