# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
name: Main build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and Test 
    runs-on: [ubuntu-latest]
    timeout-minutes: 60
    steps:
    
    - name: Checkout project
      uses: actions/checkout@v1
    
    - name: Set up Java 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    
    - name: Fetch maven cache
      uses: actions/cache@v1.1.0
      with:
        path: ~/.m2/repository
        key: gscloud-${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          gscloud-${{ runner.os }}-maven-

    - name: Update maven dependencies
      run: ./mvnw -P\!docker de.qaware.maven:go-offline-maven-plugin:resolve-dependencies --no-transfer-progress

    - name: Build without tests
      run: ./mvnw -P\!docker -ntp -Dfmt.action=check install -T1C -DskipTests

    - name: Test
      run: ./mvnw -P\!docker -ntp verify -T1C -fae

    - name: Remove project jars from cached repository
      run: |
        rm -rf .m2/repository/org/geoserver/cloud
